#!/usr/bin/env python3
"""
NavaDrummer — Backing Track Registration Helper
Run this script after adding MP3 files to assets/backing_tracks/
It updates BackingTrackService with which songs have audio available.

Usage:
  python3 register_backing_tracks.py
"""
import os, re

BACKING_DIR = "assets/backing_tracks"
SERVICE_FILE = "lib/core/backing_track_service.dart"

def scan():
    if not os.path.exists(BACKING_DIR):
        print(f"ERROR: {BACKING_DIR} not found")
        return []
    files = [f.replace(".mp3","").replace(".m4a","").replace(".aac","")
             for f in os.listdir(BACKING_DIR)
             if f.endswith((".mp3",".m4a",".aac"))]
    return sorted(files)

def update_service(song_ids):
    with open(SERVICE_FILE, "r") as f:
        c = f.read()

    # Build the new set content
    ids_str = "\n      ".join(f"\'{sid}\'," for sid in song_ids)
    new_set = f"""const withTracks = <String>{{
      // Auto-generated by register_backing_tracks.py
      {ids_str}
    }};"""

    # Replace existing set
    c = re.sub(
        r"const withTracks = <String>\{[^}]+\};",
        new_set,
        c,
        flags=re.DOTALL
    )

    with open(SERVICE_FILE, "w") as f:
        f.write(c)

if __name__ == "__main__":
    ids = scan()
    if not ids:
        print("No backing tracks found in", BACKING_DIR)
        print("Add .mp3 files named after song IDs (e.g. grande_y_fuerte.mp3)")
    else:
        print(f"Found {len(ids)} backing tracks:")
        for sid in ids:
            print(f"  ✅ {sid}")
        update_service(ids)
        print(f"\n✅ Updated {SERVICE_FILE}")
        print("Run: flutter pub get && flutter run")
